import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useEffect } from "react";
import Navbar from "../components/navbar";
import styles from "../styles/Home.module.css";
import Trees from "../public/trees.svg";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faCheck, faTimes } from "@fortawesome/free-solid-svg-icons";
import { useState } from "react/cjs/react.development";
import Footer from "../components/footer";

export default function Home() {
  useEffect(() => {
    document.querySelector("body").classList.add("body");
  });

  return (
    <div>
      <Head>
        <title>Dundas Weight Loss Clinic</title>
        <meta name="descripton" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Navbar className={styles.navbar}></Navbar>
        <header className={styles.header}>
          <div className={styles.pictureContainer}>
            <h1>Dundas Weight Loss Clinic</h1>
            <h2>
              Looking to improve the health of clients through healthy weight
              loss and other health promotion services.
            </h2>
            <p>Learn more about Heather&apos;s approach to weight loss here.</p>
            <Link href="/#about">
              <a className={styles.learnMoreButton}>Learn more</a>
            </Link>
          </div>
        </header>
        <div className={styles.bio} id="bio">
          <div className={styles.bioHeader}>
            <Image
              src="/../public/heather-headshot.jpg"
              width={300}
              height={300}
              className={styles.headerImage}
              alt="Picture of Heather Watson"
            ></Image>
            <div>
              <h2>Heather Watson</h2>
              <p>Nurse Practitioner, Yogi and Weight Councilor</p>
              <br />
              <table className={styles.contactInfo}>
                <tbody>
                  <tr>
                    <td>Address: </td>
                    <td>247 King Street West, Dundas, Ontario </td>
                  </tr>
                  <tr>
                    <td>Phone: </td>
                    <td>905-570-2610</td>
                  </tr>
                  <tr>
                    <td>Email: </td>
                    <td>dundasweightlossclinic@gmail.com</td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>
          <div className={styles.bioBody}>
            <h3>Work Experience and Schooling</h3>
            <p>
              Heather started her registered nursing career in the early 1990s
              when she graduated from the University of Toronto. Early on in her
              career, she recognized that she wanted to expand her nursing
              practice, so she completed her Masters of Nursing by the end of
              the 1990s and Nurse Practitioner-Paediatric training at the start
              of the millennium. Heather believes in lifelong learning and has
              since completed her Heart & Stroke Foundation First Aid and BLS
              Instructor Certification, CanFitPro Personal Training
              Certification, Modo Yoga Teacher Training (YTT) - 500 hrs and
              American Association of Nurse Practitioner - Obesity Management
              Fundamentals to name a few.
            </p>
            <p>
              Heather&apos;s work experience followed the trend of work
              availability in the 90s. She worked at the Hospital for Sick
              Children in almost every unit including Neurosurgery, Orthopedics,
              Trauma, General Paediatrics, IV Team, Recovery Room, Research,
              Out-patient Clinics and the Neonatal Intensive Care Unit. Her
              nurse practitioner specialization was in Neonatology where she
              worked at both the Hospital for Sick Children and McMaster
              Children&apos;s Hospital. In 2016, Heather attempted an early
              retirement with no success (dismal failure actually).{" "}
            </p>
            <p>
              When the pandemic started, she returned to work at Lynden Family
              Practice Clinic to support patient care. Quickly into her practice
              she recognized that 60-70% of the client population suffered from
              unhealthy weights and related consequences. Her physician
              colleagues supported the initiation of a weight management clinic.
              Coincidentally, Obesity Canada (National Association for Obesity
              Research, Education and Advocacy) released the Canadian Adult
              Obesity Clinical Practice Guidelines with a lot of educational
              opportunities. For 18 months, she led a weight management clinic
              with excellent results. Her clients were achieving healthy weights
              (not necessarily a BMI less than 25 ), decreased their diabetes
              medication, avoided taking or decreasing blood pressure
              medications, showed improved blood cholesterol levels, showed
              improvements in depressive symptoms etc. When the CoVid contract
              position ended at the Family Practice Clinic, she decided to go
              into private practice. Thus, Dundas Weight Loss Clinic was
              founded. Since then, she has received a Certificate of Obesity
              Management Fundamentals from the American Association of Nurse
              Practitioners and plans to complete her Lifestyle Medicine
              Professional Certification through the American Academy of
              Lifestyle Medicine.
            </p>
          </div>
        </div>
        <div className={styles.treeDiv}>
          <Trees className={styles.trees} />
        </div>
        <div className={styles.experience} id="about">
          <div className={styles.experienceBody}>
            <h2>Weight Counseling Experience</h2>
            <p>
              Heather recognizes being overweight or suffering from obesity as a
              chronic disease characterized by the accumulation of excess body
              fat that can have a negative impact on our physical, mental, or
              metabolic health as well as our overall quality of life (Obesity
              Canada, 2020). Genetic, environmental, medical and behavioral
              factors need to be considered in the assessment and management of
              unhealthy weights (AANP, 2021). Heather draws from a multitude of
              weight loss approaches depending on client medical status,
              preferences, and circumstances. Weight loss strategies are:
            </p>
            <table className={styles.experienceList}>
              <tbody>
                <tr>
                  <td>
                    <FontAwesomeIcon
                      icon={faCheck}
                      className={styles.listCheck}
                    ></FontAwesomeIcon>
                  </td>
                  <td>
                    <p>health focused</p>
                  </td>
                </tr>
                <tr>
                  <td>
                    <FontAwesomeIcon
                      icon={faCheck}
                      className={styles.listCheck}
                    ></FontAwesomeIcon>
                  </td>
                  <td>
                    <p>
                      based on medical, scientific, and experiential principles
                    </p>
                  </td>
                </tr>
                <tr>
                  <td>
                    <FontAwesomeIcon
                      icon={faCheck}
                      className={styles.listCheck}
                    ></FontAwesomeIcon>
                  </td>
                  <td>
                    <p>individualized</p>
                  </td>
                </tr>
                <tr>
                  <td>
                    <FontAwesomeIcon
                      icon={faCheck}
                      className={styles.listCheck}
                    ></FontAwesomeIcon>
                  </td>
                  <td>
                    <p>negotiable</p>
                  </td>
                </tr>
                <tr>
                  <td>
                    <FontAwesomeIcon
                      icon={faCheck}
                      className={styles.listCheck}
                    ></FontAwesomeIcon>
                  </td>
                  <td>
                    <p>
                      focused on building self-esteem, confidence, and
                      positivity
                    </p>
                  </td>
                </tr>
                <tr>
                  <td>
                    <FontAwesomeIcon
                      icon={faCheck}
                      className={styles.listCheck}
                    ></FontAwesomeIcon>
                  </td>
                  <td>
                    <p>sustainable for long term weight loss</p>
                  </td>
                </tr>
                <tr>
                  <td>
                    <FontAwesomeIcon
                      icon={faCheck}
                      className={styles.listCheck}
                    ></FontAwesomeIcon>
                  </td>
                  <td>
                    <p>
                      intended to educate the client for future, independent
                      weight management.
                    </p>
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
          <div className={styles.experienceImage}></div>
        </div>
        <span id="services"></span>
        <div className={styles.servicesContainer}>
          <div className={styles.servicesInfoContainer}>
            <h2>Services</h2>
            <p>* APPOINTMENTS MUST BE SCHEDULED IN ADVANCE *</p>
            <p className={styles.servicesInfo}>
              The initial 1-hour free consultation will be by telephone or video
              chat (Zoom, FaceTime, Messenger etc). After that, a 1-2 hour
              in-person appointment is required. In-person appointments will be
              in office or in special circumstances, in home. Appointment format
              is negotiable thereafter (telephone, video, in office or in home).
            </p>
          </div>
          <div className={styles.services}>
            <div className={styles.priceCard}>
              <h3>Free</h3>
              <p>Initial 1 hour Consultation</p>
              <table className={styles.optionsTable}>
                <tbody>
                  <tr>
                    <td>
                      <FontAwesomeIcon
                        icon={faCheck}
                        className={styles.checkmark}
                      ></FontAwesomeIcon>
                    </td>
                    <td>
                      <p>Meeting held remotely</p>
                    </td>
                  </tr>
                  <tr>
                    <td>
                      <FontAwesomeIcon
                        icon={faTimes}
                        className={styles.cross}
                      ></FontAwesomeIcon>
                    </td>
                    <td>
                      <p>Meeting held in person</p>
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>
            <div className={styles.priceCard}>
              <h3>$100 for first month</h3>
              <p>First Month Only</p>
              <table className={styles.optionsTable}>
                <tr>
                  <td>
                    <FontAwesomeIcon
                      icon={faTimes}
                      className={styles.cross}
                    ></FontAwesomeIcon>
                  </td>
                  <td>
                    <p>Meeting held remotely</p>
                  </td>
                </tr>
                <tr>
                  <td>
                    <FontAwesomeIcon
                      icon={faCheck}
                      className={styles.checkmark}
                    ></FontAwesomeIcon>
                  </td>
                  <td>
                    <p>Meeting held in person</p>
                  </td>
                </tr>
              </table>
            </div>
            <div className={styles.priceCard}>
              <h3>$25/month</h3>
              <p>Monthly Appointments</p>
              <table className={styles.optionsTable}>
                <tr>
                  <td>
                    <FontAwesomeIcon
                      icon={faCheck}
                      className={styles.checkmark}
                    ></FontAwesomeIcon>
                  </td>
                  <td>
                    <p>Meeting held remotely</p>
                  </td>
                </tr>
                <tr>
                  <td>
                    <FontAwesomeIcon
                      icon={faCheck}
                      className={styles.checkmark}
                    ></FontAwesomeIcon>
                  </td>
                  <td>
                    <p>Meeting held in person</p>
                  </td>
                </tr>
              </table>
            </div>
            <div className={styles.priceCard}>
              <h3>$50/month</h3>
              <p>Weekly or Bi-weekly Appointments</p>
              <table className={styles.optionsTable}>
                <tr>
                  <td>
                    <FontAwesomeIcon
                      icon={faCheck}
                      className={styles.checkmark}
                    ></FontAwesomeIcon>
                  </td>
                  <td>
                    <p>Meeting held remotely</p>
                  </td>
                </tr>
                <tr>
                  <td>
                    <FontAwesomeIcon
                      icon={faCheck}
                      className={styles.checkmark}
                    ></FontAwesomeIcon>
                  </td>
                  <td>
                    <p>Meeting held in person</p>
                  </td>
                </tr>
              </table>
            </div>
          </div>
        </div>
        <div className={styles.location}>
          <h2>Location</h2>
          <p>247 King Street West, Dundas, Ontario</p>
          <div className={styles.map}>
            <iframe
              src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2905.178797634249!2d-79.96720588435645!3d43.26862988523067!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x882c847e096e1389%3A0x68458c0a4681abfd!2s247%20King%20St%20W%2C%20Dundas%2C%20ON%20L9H%201V8!5e0!3m2!1sen!2sca!4v1642648064679!5m2!1sen!2sca"
              height="450"
              width={600}
              allowFullScreen=""
              loading="lazy"
              className={styles.map}
            ></iframe>
          </div>
        </div>
      </main>
      <Footer></Footer>
    </div>
  );
}
